# Alpine-based python image for lightweight
FROM python:3.13-alpine

# Set the working directory inside the container
WORKDIR /app

COPY producer.py .

# Define the command to run the producer.py script
CMD ["python", "producer.py"]
